name = "Shapefile"
uuid = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
license = "MIT"
version = "0.7.1"

[deps]
DBFTables = "75c7ada1-017a-5fb6-b8c7-2125ff2d6c93"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DBFTables = "0.2"
Tables = "0.2, 1.0"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "RemoteFiles", "Test"]
